name: build_Release
on:
  push:
    branches:
      - test
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - test
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Dependencies
        run: brew install ldid xz dpkg coreutils bartycrouch

      - name: Build
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app
          Resources/compile.release.rootless.sh

      - name: Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          name: saily_3.0
          tag_name: 3.0
          target_commitish: dev
          body: rootless_3.0
          latest: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.deb
