name: build_Release
on:
  push:
    branches:
      - dev
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - dev
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: brew install ldid xz dpkg coreutils

      - name: Build
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app
          chmod +x ./Resources/.rootless.sh
          /bin/bash -c ./Resources/.rootless.sh
          mv *.deb saily_3.0.deb

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 3.0
          tag_name: 3.0
          target_commitish: dev
          body: rootless_3.0
          latest: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.deb
